alias cdDorsata="cd ~/Projects/Dorsata/web/"
alias zshconfig="subl -w ~/.zshrc"
alias ohmyzsh="subl -w ~/.oh-my-zsh"
alias dorsataStart="cdDorsata && OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES MAX_THREADS=4 foreman start -f Procfile.dev"
alias zshalias="subl ~/.oh-my-zsh/custom/aliases.zsh"
alias lslcStart="cd ~/Projects/living-savior-lutheran/web && bundle exec jekyll serve"
alias lslcBuild="cd ~/Projects/living-savior-lutheran/web && bundle exec jekyll build"
alias lslcDeploy="gaa && gc -am \"Release $(date +%F)\" && git ftp push"
alias beep="afplay /System/Library/Sounds/Ping.aiff -v 10"
alias reload="source ~/.zshrc"
alias updateBranch="git fetch origin prerelease && git merge origin/prerelease"
alias devChrome="/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --disable-features=SameSiteByDefaultCookies,CookiesWithoutSameSiteMustBeSecure"
